### ISSUE TITLE
Interface is outdated

### ISSUE THREAD

**Issue by braxtongill** [Ovlic/kehillah.today-swiftui#4]
https://kehillah.today uses web version v0.5.2e, created on October 30th, 2022. The app uses v0.4.9, created on September 6th of the same year. Is there a way to embed the entire webpage every time, to spare you the trouble of having to update the site every time a new announcement/update happens to it? As I'm not a Swift programmer, I don't know if this is something you can natively do in the language; I recommend checking out the `<embed>` or `<iframe>` HTML tags for this if you can't.

**Comment by Ovlic** [comment]
I am considering doing this, the issue is that some parts of the HTML had to be changed to adapt and fit mobile devices. I will look into some way to do this while making it mobile-friendly.

**Comment by Ovlic** [comment]
The new version of the app should have the updated Kehillah.Today GUI. I am looking into a way to automatically update the app when a new version of the website is published.
